/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (armored-core-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80011E50u
#define func_80011E50 BootEntry  /* alias */
